spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: a96ce471a383142a16c1
            clientSecret: 7ffa4f8815e489716ab1836af259b060c265c04f
            # redirect-uri: "http://localhost:3000/login/oauth2/code/github"
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}"
          google:
            clientId: 11
            clientSecret: 111
# ...